apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
  labels:
    managed-by: argocd
    environment: production
    team: platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    description: "Example namespace managed by ArgoCD"
    created-by: "GitOps PR Process"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: example-namespace
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-limits
  namespace: example-namespace
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: example-namespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
